---
version: '0.0.1'
services:
  mnms-backend:
    image: mnms-backend:latest
    container_name: mnms-backend
    build:
      context: .
      dockerfile: DockerfileBackend
    environment:
      - ADMIN_PASSWORD=1234
      - AUTH_SECRET_KEY=3487783de8057b7527d133644e25ec84419179ab5a8287215d04d894bbb1e731
      - CACHING_ENABLED=0
    ports:
      - 8000:80
    volumes:
      - ./backend/db:/db
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  mnms-frontend:
    image: mnms-frontend:latest
    container_name: mnms-frontend
    build:
      context: .
      dockerfile: DockerfileFrontend
    environment:
      - PUBLIC_API_PATH=http://your-api-ip:8000
    ports:
      - 80:3000
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
