---
version: '0.0.1'
services:
  mnms-backend:
    image: mnms-backend:latest
    container_name: mnms-backend
    build:
      context: .
      dockerfile: DockerfileBackend
    environment:
      - ADMIN_PASSWORD=1234
    ports:
      - 8000:80
    volumes:
      - ./backend/db:/db
    restart: unless-stopped

  mnms-frontend:
    image: mnms-frontend:latest
    container_name: mnms-frontend
    build:
      context: .
      dockerfile: DockerfileFrontend
    environment:
      - PUBLIC_API_PATH=http://your-api-ip:8000
    ports:
      - 80:3000
    extra_hosts:
    - "host.docker.internal:host-gateway"
    restart: unless-stopped
